# Generated by Django 4.2.5 on 2023-12-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_watchlist_comments_bids"),
    ]

    operations = [
        migrations.RenameModel(old_name="Bids", new_name="Bid",),
        migrations.RenameModel(old_name="Comments", new_name="Comment",),
    ]
