# Generated by Django 4.2.5 on 2023-12-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_bids_bid_rename_comments_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="starting_bid",
            field=models.IntegerField(default=0, max_length=10000),
        ),
    ]
