# Generated by Django 4.2.5 on 2023-12-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listing_starting_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid", old_name="listing_id", new_name="listing",
        ),
        migrations.RenameField(model_name="bid", old_name="user_id", new_name="user",),
        migrations.RenameField(
            model_name="comment", old_name="listing_id", new_name="listing",
        ),
        migrations.RenameField(
            model_name="comment", old_name="user_id", new_name="user",
        ),
        migrations.RenameField(
            model_name="listing", old_name="user_id", new_name="user",
        ),
        migrations.RenameField(
            model_name="watchlist", old_name="listing_id", new_name="listing",
        ),
        migrations.RenameField(
            model_name="watchlist", old_name="user_id", new_name="user",
        ),
    ]
