# Generated by Django 4.2.5 on 2023-12-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_rename_listing_id_bid_listing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing", name="image_url", field=models.URLField(blank=True),
        ),
    ]
