# Generated by Django 4.2.5 on 2023-12-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="ammount",
            field=models.IntegerField(max_length=100000, null=True),
        ),
    ]
