# Generated by Django 4.2.5 on 2023-12-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_bid_ammount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid", old_name="ammount", new_name="amount",
        ),
    ]
