# Generated by Django 4.2.5 on 2023-12-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_listing_winning_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="winning_bid",
            field=models.IntegerField(blank=True, max_length=10000, null=True),
        ),
    ]
