# Generated by Django 4.2.5 on 2023-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_alter_listing_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="current_bid",
            field=models.IntegerField(blank=True, max_length=10000, null=True),
        ),
    ]
