# Generated by Django 4.2.5 on 2023-12-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_listing_current_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing", old_name="current_bid", new_name="current_price",
        ),
    ]
